"""Shared fixtures and helpers for E2E tests."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_CASES_DIR = Path(__file__).resolve().parent / "cases"
_ARTIFACTS_DIR = _REPO_ROOT / ".artifacts" / "e2e"


@pytest.fixture(scope="session")
def artifacts_root():
    """Ensure .artifacts/e2e/ directory exists at repo root."""
    _ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    return _ARTIFACTS_DIR


def _run_case(
    case_id: str,
    artifacts_root: Path,
    *,
    cli_flags: list[str] | None = None,
    source_bytes: bytes | None = None,
    target_bytes: bytes | None = None,
) -> tuple[int, dict]:
    """Run a single E2E case via subprocess and return (exit_code, report_dict).

    Reads tests/e2e/cases/<case_id>/config.yaml, resolves source/target paths
    to the fixture directory, writes a resolved config into .artifacts/e2e/<case_id>/,
    runs the CLI, and loads the resulting report.json.

    For cases that need runtime-generated files (e.g. CRLF), pass source_bytes
    and/or target_bytes to write them into the artifacts dir instead.
    """
    case_dir = _CASES_DIR / case_id
    out_dir = artifacts_root / case_id

    # Clean previous outputs for this case only
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    # Read fixture config
    config = yaml.safe_load((case_dir / "config.yaml").read_text())

    # Resolve source/target: use runtime-generated bytes or fixture files
    for key, override in (("source", source_bytes), ("target", target_bytes)):
        if override is not None:
            gen_path = out_dir / f"{key}.txt"
            gen_path.write_bytes(override)
            config[key] = str(gen_path)
        else:
            rel = config.get(key, "")
            if rel and not Path(rel).is_absolute():
                config[key] = str(case_dir / rel)

    # Write resolved config
    resolved_config = out_dir / "config.yaml"
    with open(resolved_config, "w") as f:
        yaml.dump(config, f, default_flow_style=False)

    report_path = out_dir / "report.json"

    cmd = [
        sys.executable,
        "-m",
        "reconify",
        "run",
        str(resolved_config),
        "--out",
        str(report_path),
    ]
    if cli_flags:
        cmd.extend(cli_flags)

    result = subprocess.run(cmd, capture_output=True, text=True)

    report: dict = {}
    if report_path.exists():
        report = json.loads(report_path.read_text())

    return result.returncode, report


@pytest.fixture(scope="session")
def e2e_runner(artifacts_root):
    """Return a callable that runs an E2E case and returns (exit_code, report)."""

    def _run(
        case_id: str,
        *,
        cli_flags: list[str] | None = None,
        source_bytes: bytes | None = None,
        target_bytes: bytes | None = None,
    ) -> tuple[int, dict]:
        return _run_case(
            case_id,
            artifacts_root,
            cli_flags=cli_flags,
            source_bytes=source_bytes,
            target_bytes=target_bytes,
        )

    return _run
